fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
        types: [yaml]
      - id: end-of-file-fixer
        types: [text]
        stages: [pre-commit, pre-push, manual]

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.16
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/crate-ci/typos
    rev: typos-dict-v0.11.37
    hooks:
      - id: typos
        exclude: 'CHANGELOG.md'

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.5
    hooks:
      - id: ruff
        args: [--fix]
        types: [python]
      - id: ruff-format
        types: [python]
